time_left_turn: 6.5
time_straight_turn: 10
time_right_turn: 3

ff_left: 0.3
ff_straight: 0.03
ff_right: -0.4

LFparams_left: {phi_max: -0.1, phi_min: -0.2, range_est: 0.4, red_to_white: true, use_yellow: false}
LFparams_straight: { phi_max: 0.07, phi_min: -0.07, red_to_white: false}
LFparams_right: {phi_max: 0.2, phi_min: 0.1, range_est: 0.4, red_to_white: false, use_yellow: true}

omega_min_left: 0.2
omega_max_left: 0.6
omega_min_straight: -0.1
omega_max_straight: 0.1
omega_min_right: -2.5
omega_max_right: 999

debug_dir: -1
